name: "publish packages"

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - '.github/workflows/publish.yml'
      - '*.props'

  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    environment: nuget.org
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: restore .NET
        run: dotnet restore Phazor.sln

      - name: restore Node
        run: |
          cd src/Phazor.Components/javascript
          yarn install

      - name: build
        run: dotnet build Phazor.sln -c Release --no-restore /p:PatchVersion=${{ github.run_number }}

      - name: move packages
        run: |
          rm -rf .packages
          mkdir .packages
          mv src/Phazor.Components/bin/Release/*.nupkg .packages/
          mv src/Phazor.Extensions/bin/Release/*.nupkg .packages/
          mv src/Phazor.Reactive/bin/Release/*.nupkg .packages/
          mv src/Phazor.Reactive.Abstractions/bin/Release/*.nupkg .packages/
          mv src/Phazor.Reactive.Generators/bin/Release/*.nupkg .packages/  

      - name: publish to GitHub nuget repository
        run: |
          for file in .packages/*.nupkg
          do
            dotnet nuget push "${file#/}" --source "nuget.org" --api-key ${{ secrets.NUGET_API_KEY }}
          done